### ISSUE TITLE
Agregar una estrofa

### ISSUE THREAD

**Issue by Eder-Arredondo** [Eder-Arredondo/Percepcion-N6-Eq.8#2]
Puedes Agregar una estrofa sobre el poema del día y la noche?

![tarde](https://user-images.githubusercontent.com/42302773/44304701-d86f6b00-a328-11e8-89ee-e6d44859da75.jpg)

**Comment by brayaneli1** [comment]
claro que si

**Comment by brayaneli1** [comment]
luego, poco a poco,
se va escondiendo
y cuando es muy tarde
se queda durmiendo

**Comment by brayaneli1** [comment]
se agrego nueva estrofa al poema del dia y la noche
